# Generated by Django 6.1.1 on 2026-09-21 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_branchcommercialsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('warehouse_requests', 'Warehouse requests'), ('warehouse_inbound', 'Incoming from branches'), ('warehouse_returns', 'Returned dispatches'), ('branch_receipts', 'Branch receipts')], db_index=True, max_length=32)),
                ('last_seen_at', models.DateTimeField()),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_section_cursors', to='branches.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_section_cursors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'section', 'branch'], name='inbox_cursor_lookup_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('user', 'section'), name='unique_inbox_cursor_warehouse'), models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('user', 'section', 'branch'), name='unique_inbox_cursor_branch')],
            },
        ),
    ]
