# Generated by Django 6.1 on 2026-08-23 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('products', '0009_subfamily'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequestThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('awaiting_warehouse', 'Awaiting warehouse'), ('awaiting_branch', 'Awaiting branch'), ('closed', 'Closed')], default='awaiting_warehouse', max_length=20)),
                ('last_activity_at', models.DateTimeField(help_text='Denormalized: bumped on every create/post/close (D5 philosophy).')),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, choices=[('request_satisfied', 'Request Satisfied'), ('other', 'Other')], max_length=30)),
                ('close_reason_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_threads', to='branches.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_threads_closed', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(blank=True, help_text='Traceability: items created from this thread, linked by the warehouse.', related_name='request_threads', to='products.item')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_threads_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemRequestThreadChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('item_linked', 'Item linked'), ('closed', 'Closed')], max_length=30)),
                ('changes', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_logs', to='threads.itemrequestthread')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_thread_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('branch', 'Branch'), ('warehouse', 'Warehouse')], help_text='Explicit poster side — never inferred from identity (dual users exist).', max_length=16)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thread_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='threads.itemrequestthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='threads.itemrequestthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_read_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='itemrequestthread',
            index=models.Index(fields=['branch', 'status'], name='thread_branch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='itemrequestthread',
            index=models.Index(fields=['-last_activity_at'], name='thread_last_activity_idx'),
        ),
        migrations.AddConstraint(
            model_name='threadreadstate',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='unique_thread_read_state'),
        ),
    ]
