# Generated by Django 6.1 on 2026-08-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequestthread',
            name='satisfaction',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=1, help_text="Opener's satisfaction (1–5 stars), set at close. Default 1 star so an unattended request can signal dissatisfaction."),
        ),
    ]
