from django.urls import path

from . import console_views

urlpatterns = [
    path(
        "manage/goods-receipts/",
        console_views.manage_goods_receipt_list,
        name="manage_goods_receipt_list",
    ),
    path(
        "manage/goods-receipts/<int:receipt_id>/",
        console_views.manage_goods_receipt_detail,
        name="manage_goods_receipt_detail",
    ),
    path(
        "manage/purchase-orders/<int:po_id>/receipt-summary/",
        console_views.manage_receipt_summary,
        name="manage_receipt_summary",
    ),
    path(
        "manage/stock-movements/",
        console_views.manage_stock_movements,
        name="manage_stock_movements",
    ),
    path(
        "manage/stock-adjustments/",
        console_views.manage_stock_adjustment,
        name="manage_stock_adjustment",
    ),
    path(
        "branch/receipts/",
        console_views.branch_receipt_history_list,
        name="branch_receipt_history_list",
    ),
    path(
        "branch/receipts/issues/",
        console_views.branch_receipt_issue_list,
        name="branch_receipt_issue_list",
    ),
    path(
        "branch/receipts/issues/<int:issue_id>/",
        console_views.branch_receipt_issue_detail,
        name="branch_receipt_issue_detail",
    ),
    path(
        "branch/receipts/issues/<int:issue_id>/receive/",
        console_views.branch_receipt_receive,
        name="branch_receipt_receive",
    ),
    path(
        "branch/receipts/issues/<int:issue_id>/short-close/",
        console_views.branch_receipt_short_close,
        name="branch_receipt_short_close",
    ),
    path(
        "branch/receipts/issues/<int:issue_id>/return/",
        console_views.branch_receipt_return,
        name="branch_receipt_return",
    ),
    path(
        "branch/receipts/returns/",
        console_views.branch_dispatch_return_history_list,
        name="branch_dispatch_return_history_list",
    ),
    path(
        "branch/stock/",
        console_views.branch_stock_list,
        name="branch_stock_list",
    ),
    path(
        "branch/stock/movements/",
        console_views.branch_stock_movement_list,
        name="branch_stock_movement_list",
    ),
    path(
        "branch/stock/adjust/",
        console_views.branch_stock_adjust,
        name="branch_stock_adjust",
    ),
    path(
        "branch/consumption/",
        console_views.branch_consumption_list,
        name="branch_consumption_list",
    ),
    path(
        "branch/consumption/<int:consumption_id>/",
        console_views.branch_consumption_detail,
        name="branch_consumption_detail",
    ),
    path(
        "manage/alerts/",
        console_views.manage_alerts_list,
        name="manage_alerts_list",
    ),
    path(
        "manage/alerts/<int:receipt_id>/mark-read/",
        console_views.manage_alerts_mark_read,
        name="manage_alerts_mark_read",
    ),
    path(
        "manage/alerts/events/<int:alert_id>/mark-read/",
        console_views.manage_alerts_event_mark_read,
        name="manage_alerts_event_mark_read",
    ),
    path(
        "branch/alerts/",
        console_views.branch_alerts_list,
        name="branch_alerts_list",
    ),
    path(
        "branch/alerts/<int:receipt_id>/mark-read/",
        console_views.branch_alerts_mark_read,
        name="branch_alerts_mark_read",
    ),
    path(
        "branch/alerts/events/<int:alert_id>/mark-read/",
        console_views.branch_alerts_event_mark_read,
        name="branch_alerts_event_mark_read",
    ),
    path(
        "branch/send-to-warehouse/",
        console_views.branch_send_to_warehouse_list,
        name="branch_send_to_warehouse_list",
    ),
    path(
        "branch/send-to-warehouse/<int:shipment_id>/",
        console_views.branch_send_to_warehouse_detail,
        name="branch_send_to_warehouse_detail",
    ),
    path(
        "branch/send-to-warehouse/<int:shipment_id>/cancel/",
        console_views.branch_send_to_warehouse_cancel,
        name="branch_send_to_warehouse_cancel",
    ),
    path(
        "manage/incoming-from-branches/",
        console_views.manage_inbound_from_branches_list,
        name="manage_inbound_from_branches_list",
    ),
    path(
        "manage/incoming-from-branches/<int:shipment_id>/",
        console_views.manage_inbound_from_branches_detail,
        name="manage_inbound_from_branches_detail",
    ),
    path(
        "manage/incoming-from-branches/<int:shipment_id>/receive/",
        console_views.manage_inbound_from_branches_receive,
        name="manage_inbound_from_branches_receive",
    ),
    path(
        "manage/stock-at-branches/",
        console_views.manage_stock_at_branches,
        name="manage_stock_at_branches",
    ),
    path(
        "manage/returned-dispatches/",
        console_views.manage_dispatch_return_list,
        name="manage_dispatch_return_list",
    ),
    path(
        "manage/returned-dispatches/<int:dispatch_return_id>/",
        console_views.manage_dispatch_return_detail,
        name="manage_dispatch_return_detail",
    ),
    path(
        "manage/returned-dispatches/<int:dispatch_return_id>/process/",
        console_views.manage_dispatch_return_process,
        name="manage_dispatch_return_process",
    ),
]
