# Generated by Django 6.1 on 2026-08-24 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoicePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('tag', models.CharField(blank=True, choices=[('praise', 'Praise'), ('concern', 'Concern'), ('suggestion', 'Suggestion'), ('wish', 'Wish')], max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voice_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceSubThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_thread', to='company_voice.voicepost')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voice_comments', to=settings.AUTH_USER_MODEL)),
                ('sub_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='company_voice.voicesubthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='voicepost',
            index=models.Index(fields=['created_at'], name='voice_post_created_idx'),
        ),
        migrations.AddIndex(
            model_name='voicepost',
            index=models.Index(fields=['deleted_at'], name='voice_post_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesubthread',
            index=models.Index(fields=['deleted_at'], name='voice_subthread_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecomment',
            index=models.Index(fields=['created_at'], name='voice_comment_created_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecomment',
            index=models.Index(fields=['deleted_at'], name='voice_comment_deleted_idx'),
        ),
    ]
