# Generated by Django 6.1 on 2026-08-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Europe/Lisbon', help_text='IANA timezone name, e.g. Europe/Lisbon (UTC+1 summer / UTC+0 winter) or Asia/Singapore (UTC+8). Used for server-rendered dates.', max_length=64),
        ),
    ]
