# Generated by Django 6.1 on 2026-08-21 10:07

from django.db import migrations, models


def sync_groups(apps, schema_editor):
    from accounts.groups import sync_warehouse_groups

    sync_warehouse_groups()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_timezone'),
        ('products', '0001_initial'),
        ('procurement', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='warehouse_grade',
            field=models.PositiveSmallIntegerField(default=1, help_text='Grade within the warehouse group: operator 1–2, manager 1–3. warehouse_admins ignore this (always treated as 1 / unlimited).'),
        ),
        migrations.RunPython(sync_groups, migrations.RunPython.noop),
    ]
