# Generated by Django 6.1 on 2026-08-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_warehouse_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Email verified by Google (Google verifies emails).'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_google_account',
            field=models.BooleanField(default=False, help_text='True once the user has authenticated via Google OAuth.'),
        ),
    ]
