# Generated by Django 6.1 on 2026-08-21 18:14

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_branch_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='BranchMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('operator', 'Operator'), ('manager', 'Manager'), ('admin', 'Admin')], default='operator', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='branches.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['branch__name', 'user__email'],
                'constraints': [models.UniqueConstraint(fields=('user', 'branch'), name='unique_branch_membership_user_branch')],
            },
        ),
    ]
