# Generated by Django 6.1 on 2026-08-29

from django.db import migrations, models


def create_default_settings(apps, schema_editor):
    BranchCommercialSettings = apps.get_model("branches", "BranchCommercialSettings")
    BranchCommercialSettings.objects.get_or_create(
        pk=1,
        defaults={"mode": "unpriced"},
    )


def drop_default_settings(apps, schema_editor):
    BranchCommercialSettings = apps.get_model("branches", "BranchCommercialSettings")
    BranchCommercialSettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchCommercialSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("unpriced", "Unpriced — quantity only"),
                            ("priced", "Priced — selling prices and EUR caps"),
                        ],
                        default="unpriced",
                        max_length=16,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "branch commercial settings",
                "verbose_name_plural": "branch commercial settings",
            },
        ),
        migrations.RunPython(create_default_settings, drop_default_settings),
    ]
