# Generated by Django 6.1 on 2026-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement_stockmovement_reference_both_or_neither'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('goods_issue', 'Goods issue'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
