# Generated by Django 6.1 on 2026-08-21 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovement_movement_type'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('internal_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_issues', to='orders.internalrequest')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'permissions': [('can_issue_goods', 'Can issue goods to branches')],
            },
        ),
        migrations.CreateModel(
            name='GoodsIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.DecimalField(decimal_places=3, max_digits=12)),
                ('goods_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.goodsissue')),
                ('internal_request_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_lines', to='orders.internalrequestline')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('goods_issue', 'internal_request_line'), name='unique_goods_issue_line')],
            },
        ),
    ]
