# Generated by Django 6.1 on 2026-08-21 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0004_goodsissue_goodsissueline'),
        ('products', '0008_alter_item_reorder_level_alter_item_retail_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('goods_issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_receipts', to='inventory.goodsissue')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchItemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_stock', to='branches.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_stock', to='products.item')),
            ],
            options={
                'ordering': ['branch', 'item'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'item'), name='unique_branch_item_stock'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='branch_item_stock_gte_zero')],
            },
        ),
        migrations.CreateModel(
            name='BranchReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=3, max_digits=12)),
                ('branch_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.branchreceipt')),
                ('goods_issue_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_receipt_lines', to='inventory.goodsissueline')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('branch_receipt', 'goods_issue_line'), name='unique_branch_receipt_line')],
            },
        ),
        migrations.CreateModel(
            name='BranchStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Signed quantity: positive in, negative out.', max_digits=12)),
                ('movement_type', models.CharField(choices=[('receipt', 'Receipt'), ('adjustment', 'Adjustment')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='branches.branch')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_stock_movements', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_stock_movements', to='products.item')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'item', '-created_at'], name='inventory_b_branch__b8826c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('content_type__isnull', True), ('object_id__isnull', True)), models.Q(('content_type__isnull', False), ('object_id__isnull', False)), _connector='OR'), name='branchstockmovement_reference_both_or_neither')],
            },
        ),
    ]
