# Generated by Django 6.1.1 on 2026-09-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_branchreceipt_branchitemstock_branchreceiptline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchitemstock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branchreceiptline',
            name='quantity_received',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='branchstockmovement',
            name='quantity',
            field=models.IntegerField(help_text='Signed quantity: positive in, negative out.'),
        ),
        migrations.AlterField(
            model_name='goodsissueline',
            name='quantity_issued',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='quantity_received',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(help_text='Signed quantity: positive in, negative out.'),
        ),
    ]
