# Generated by Django 6.1.1 on 2026-09-20 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branchcommercialsettings'),
        ('inventory', '0008_branchreceipt_follow_up_and_readstate'),
        ('products', '0012_rename_vat16_code_to_vat14'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchstockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('adjustment', 'Adjustment'), ('consumption', 'Consumption')], max_length=20),
        ),
        migrations.CreateModel(
            name='BranchConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='branches.branch')),
                ('consumed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_consumptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-consumed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BranchConsumptionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.branchconsumption')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_consumption_lines', to='products.item')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('consumption', 'item'), name='unique_branch_consumption_line'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='branch_consumption_line_qty_gte_one')],
            },
        ),
    ]
