# Generated by Django 6.1.1 on 2026-09-20 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branchcommercialsettings'),
        ('inventory', '0009_branchconsumption'),
        ('products', '0012_rename_vat16_code_to_vat14'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchstockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('adjustment', 'Adjustment'), ('consumption', 'Consumption'), ('send_to_warehouse', 'Send to warehouse')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('goods_issue', 'Goods issue'), ('adjustment', 'Adjustment'), ('branch_inbound', 'From branch')], max_length=20),
        ),
        migrations.CreateModel(
            name='BranchWarehouseShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_transit', 'In transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='in_transit', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('receive_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_shipments', to='branches.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_warehouse_shipments_cancelled', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_warehouse_shipments_received', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_warehouse_shipments_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BranchWarehouseShipmentChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('received', 'Received'), ('cancelled', 'Cancelled')], max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='inventory.branchwarehouseshipment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_warehouse_shipment_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BranchWarehouseShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sent', models.IntegerField()),
                ('quantity_received', models.IntegerField(default=0)),
                ('quantity_written_off', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_warehouse_shipment_lines', to='products.item')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.branchwarehouseshipment')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('shipment', 'item'), name='unique_branch_warehouse_shipment_line'), models.CheckConstraint(condition=models.Q(('quantity_sent__gte', 1)), name='bws_line_sent_gte_one'), models.CheckConstraint(condition=models.Q(('quantity_received__gte', 0)), name='bws_line_received_gte_zero'), models.CheckConstraint(condition=models.Q(('quantity_written_off__gte', 0)), name='bws_line_written_off_gte_zero')],
            },
        ),
    ]
