# Generated by Django 6.1.1 on 2026-09-21 09:58

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branchcommercialsettings'),
        ('inventory', '0010_branch_warehouse_shipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('goods_issue', 'Goods issue'), ('adjustment', 'Adjustment'), ('branch_inbound', 'From branch'), ('dispatch_return', 'Dispatch return')], max_length=20),
        ),
        migrations.CreateModel(
            name='DispatchReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_transit', 'In transit'), ('processed', 'Processed')], db_index=True, default='in_transit', max_length=20)),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('return_reason', models.CharField(max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('process_reason', models.CharField(blank=True, max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_returns', to='branches.branch')),
                ('goods_issue', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_return', to='inventory.goodsissue')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_returns_processed', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_returns_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-returned_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DispatchReturnChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('returned', 'Returned'), ('restocked', 'Restocked'), ('written_off', 'Written off')], max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='inventory.dispatchreturn')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_return_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('dispatch_return_opened', 'Dispatch return opened'), ('dispatch_return_restocked', 'Dispatch return restocked'), ('dispatch_return_written_off', 'Dispatch return written off')], db_index=True, max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_alerts', to='branches.branch')),
                ('dispatch_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.dispatchreturn')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DispatchReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.IntegerField()),
                ('quantity_restocked', models.IntegerField(default=0)),
                ('quantity_written_off', models.IntegerField(default=0)),
                ('dispatch_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.dispatchreturn')),
                ('goods_issue_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_return_lines', to='inventory.goodsissueline')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('dispatch_return', 'goods_issue_line'), name='unique_dispatch_return_line'), models.CheckConstraint(condition=models.Q(('quantity_returned__gte', 1)), name='dispatch_return_line_returned_gte_one'), models.CheckConstraint(condition=models.Q(('quantity_restocked__gte', 0)), name='dispatch_return_line_restocked_gte_zero'), models.CheckConstraint(condition=models.Q(('quantity_written_off__gte', 0)), name='dispatch_return_line_written_off_gte_zero'), models.CheckConstraint(condition=models.Q(('quantity_restocked__lte', django.db.models.expressions.CombinedExpression(models.F('quantity_returned'), '-', models.F('quantity_written_off')))), name='dispatch_return_line_processed_lte_returned')],
            },
        ),
        migrations.CreateModel(
            name='InventoryAlertReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='inventory.inventoryalert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alert_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('alert', 'user'), name='unique_inventory_alert_read_state')],
            },
        ),
    ]
