"""Structured dev seed data for items, families, and suppliers."""

FAMILIES = (
    {"name": "Cement", "is_active": True},
    {"name": "Aggregates", "is_active": True},
    {"name": "Pipes", "is_active": True},
    {"name": "Steel", "is_active": True},
    {"name": "Timber", "is_active": True},
    {"name": "Tools", "is_active": True},
    {"name": "Electrical", "is_active": True},
    {"name": "Plumbing", "is_active": True},
    {"name": "Paint", "is_active": True},
    {"name": "Safety", "is_active": True},
    {"name": "Fasteners", "is_active": True},
    {"name": "Misc", "is_active": True},
    {"name": "Legacy stock", "is_active": False},
)

# name, parent family (skip inactive families such as Legacy stock)
SUB_FAMILIES = (
    {"name": "Bags", "family": "Cement"},
    {"name": "Bulk", "family": "Cement"},
    {"name": "Steel", "family": "Pipes"},
    {"name": "PVC", "family": "Pipes"},
    {"name": "Cables", "family": "Electrical"},
    {"name": "PPE", "family": "Safety"},
)

# internal_code, sub_family name, family name
ITEM_SUB_FAMILIES = (
    ("CEM-50", "Bags", "Cement"),
    ("PIPE-20", "Steel", "Pipes"),
    ("PIPE-50", "PVC", "Pipes"),
    ("CABLE-2.5", "Cables", "Electrical"),
    ("GLOVES-L", "PPE", "Safety"),
)

SUPPLIERS = (
    {
        "name": "BuildSupply Ltd",
        "phone": "+351 210 000 001",
        "contact_name": "Ana Ribeiro",
        "email": "sales@buildsupply.dev",
        "is_active": True,
    },
    {
        "name": "Porto Materials Co",
        "email": "sales@portomaterials.dev",
        "contact_name": "Carlos Mendes",
        "is_active": True,
    },
    {
        "name": "National Cement Works",
        "phone": "+351 220 000 002",
        "contact_name": "Warehouse desk",
        "is_active": True,
    },
    {
        "name": "Iberian Steel Trading",
        "phone": "+351 221 000 003",
        "contact_name": "Joao Silva",
        "is_active": True,
    },
    {
        "name": "Norte Timber Supply",
        "email": "orders@nortetimber.dev",
        "is_active": True,
    },
    {
        "name": "ElectroPorto",
        "phone": "+351 222 000 004",
        "contact_name": "Maria Costa",
        "is_active": True,
    },
    {
        "name": "AquaFlow Plumbing",
        "email": "supply@aquaflow.dev",
        "is_active": True,
    },
    {
        "name": "ColorWorks Paint",
        "phone": "+351 223 000 005",
        "is_active": True,
    },
    {
        "name": "SafeGuard Equipment",
        "contact_name": "Pedro Alves",
        "is_active": True,
    },
    {
        "name": "FixAll Fasteners",
        "email": "bulk@fixall.dev",
        "is_active": True,
    },
    {
        "name": "Old Suppliers Inc",
        "notes": "Inactive — do not order",
        "is_active": False,
    },
    {
        "name": "Closed Warehouse Deals",
        "notes": "Company closed",
        "is_active": False,
    },
)

# supplier_name, internal_code, cost_price, primary
SUPPLIER_ITEM_PRICES = (
    ("National Cement Works", "CEM-50", "8.50", True),
    ("National Cement Works", "CEM-25", "4.95", False),
    ("National Cement Works", "CEM-40", "9.80", False),
    ("BuildSupply Ltd", "CEM-50", "8.75", False),
    ("BuildSupply Ltd", "PIPE-20", "3.10", True),
    ("BuildSupply Ltd", "STEEL-8", "2.40", False),
    ("Porto Materials Co", "SAND-1KG", "0.90", True),
    ("Porto Materials Co", "GRAVEL-10", "1.20", False),
    ("Iberian Steel Trading", "STEEL-6", "1.85", False),
    ("Iberian Steel Trading", "STEEL-10", "2.90", True),
    ("Norte Timber Supply", "TIMBER-2X4", "2.15", True),
    ("Norte Timber Supply", "TIMBER-PLY", "12.50", False),
    ("ElectroPorto", "CABLE-2.5", "28.00", True),
    ("ElectroPorto", "SOCKET", "1.40", False),
    ("AquaFlow Plumbing", "VALVE-15", "2.60", True),
    ("AquaFlow Plumbing", "TAP-CHROME", "18.90", False),
    ("ColorWorks Paint", "PAINT-WHITE", "16.40", True),
    ("ColorWorks Paint", "PAINT-RED", "8.20", False),
    ("SafeGuard Equipment", "GLOVES-L", "1.95", True),
    ("SafeGuard Equipment", "HELMET", "4.60", False),
    ("FixAll Fasteners", "BOLT-M8", "0.55", True),
    ("FixAll Fasteners", "SCREW-50", "1.15", False),
)

# internal_code, description, family, unit, reorder_level, is_active, vat_rate_code
ITEMS = (
    ("CEM-50", "Cement 50kg", "Cement", "kg", "20", True, "VAT16"),
    ("CEM-25", "Cement 25kg", "Cement", "kg", "15", True, "VAT16"),
    ("CEM-40", "Cement 40kg rapid", "Cement", "kg", "25", True, "VAT16"),
    ("CEM-WHITE", "White cement 25kg", "Cement", "kg", "10", True, "VAT16"),
    ("CEM-OLD", "Cement discontinued bag", "Cement", "kg", "0", False, "VAT16"),
    ("SAND-1KG", "Sand 1kg", "Aggregates", "kg", "50", True, "VAT16"),
    ("GRAVEL-10", "Gravel 10mm bulk", "Aggregates", "kg", "30", True, "VAT16"),
    ("GRAVEL-20", "Gravel 20mm bulk", "Aggregates", "kg", "40", True, "VAT16"),
    ("SAND-FINE", "Fine sand bag 25kg", "Aggregates", "kg", "0", True, "VAT16"),
    ("SAND-OLD", "Old sand stock", "Aggregates", "kg", "0", False, "VAT16"),
    ("PIPE-20", "Steel pipe 20mm", "Pipes", "m", "20", True, "VAT16"),
    ("PIPE-32", "Steel pipe 32mm", "Pipes", "m", "15", True, "VAT16"),
    ("PIPE-50", "PVC pipe 50mm", "Pipes", "m", "25", True, "VAT16"),
    ("PIPE-OLD", "Obsolete pipe 15mm", "Pipes", "m", "0", False, "VAT16"),
    ("STEEL-6", "Steel bar 6mm", "Steel", "m", "50", True, "VAT16"),
    ("STEEL-8", "Steel bar 8mm", "Steel", "m", "40", True, "VAT16"),
    ("STEEL-10", "Steel bar 10mm", "Steel", "m", "30", True, "VAT16"),
    ("STEEL-PLATE", "Steel plate 2mm", "Steel", "m2", "10", True, "VAT16"),
    ("STEEL-OLD", "Rusty steel bar 12mm", "Steel", "m", "0", False, "VAT16"),
    ("TIMBER-2X4", "Timber 2x4 3m", "Timber", "m", "15", True, "VAT16"),
    ("TIMBER-2X6", "Timber 2x6 3m", "Timber", "m", "10", True, "VAT16"),
    ("TIMBER-PLY", "Plywood sheet 12mm", "Timber", "m2", "8", True, "VAT16"),
    ("TIMBER-OLD", "Damaged timber bundle", "Timber", "m", "0", False, "VAT16"),
    ("HAMMER", "Claw hammer 500g", "Tools", "piece", "5", True, "VAT16"),
    ("DRILL-18", "Drill bit set 18pc", "Tools", "piece", "3", True, "VAT16"),
    ("SAW-CIRC", "Circular saw blade 190mm", "Tools", "piece", "8", True, "VAT16"),
    ("LEVEL-60", "Spirit level 60cm", "Tools", "piece", "0", True, "VAT16"),
    ("TOOL-OLD", "Broken chisel set", "Tools", "piece", "0", False, "VAT16"),
    ("CABLE-2.5", "Cable 2.5mm 100m", "Electrical", "m", "20", True, "VAT16"),
    ("CABLE-1.5", "Cable 1.5mm 100m", "Electrical", "m", "15", True, "VAT16"),
    ("SOCKET", "Double socket white", "Electrical", "piece", "20", True, "VAT16"),
    ("SWITCH-1G", "Light switch 1 gang", "Electrical", "piece", "0", True, "VAT16"),
    ("ELEC-OLD", "Old fuse box", "Electrical", "piece", "0", False, "VAT16"),
    ("VALVE-15", "Ball valve 15mm", "Plumbing", "piece", "10", True, "VAT16"),
    ("TAP-CHROME", "Chrome tap mixer", "Plumbing", "piece", "12", True, "VAT16"),
    ("FIT-90", "Elbow fitting 90deg 20mm", "Plumbing", "piece", "50", True, "VAT16"),
    ("PIPE-PEX", "PEX pipe 16mm", "Plumbing", "m", "0", True, "VAT16"),
    ("PLUMB-OLD", "Leaky tap stock", "Plumbing", "piece", "0", False, "VAT16"),
    ("PAINT-WHITE", "Interior paint white 10L", "Paint", "l", "8", True, "VAT16"),
    ("PAINT-GRAY", "Exterior paint gray 10L", "Paint", "l", "6", True, "VAT16"),
    ("PAINT-RED", "Metal paint red 2.5L", "Paint", "l", "10", True, "VAT16"),
    ("PAINT-PRIMER", "Wood primer 5L", "Paint", "l", "0", True, "VAT16"),
    ("PAINT-OLD", "Expired paint bucket", "Paint", "l", "0", False, "VAT16"),
    ("GLOVES-L", "Work gloves size L", "Safety", "piece", "30", True, "VAT16"),
    ("HELMET", "Safety helmet yellow", "Safety", "piece", "10", True, "VAT16"),
    ("GOGGLES", "Safety goggles clear", "Safety", "piece", "15", True, "VAT16"),
    ("VEST-HIVIS", "Hi-vis vest orange", "Safety", "piece", "0", True, "VAT16"),
    ("SAFE-OLD", "Torn gloves batch", "Safety", "piece", "0", False, "VAT16"),
    ("BOLT-M8", "Bolt M8 x 50 pack 100", "Fasteners", "piece", "20", True, "VAT16"),
    ("NUT-M8", "Nut M8 pack 100", "Fasteners", "piece", "25", True, "VAT16"),
    ("SCREW-50", "Wood screws 50mm box", "Fasteners", "piece", "30", True, "VAT16"),
    ("WASHER-M8", "Washer M8 pack 100", "Fasteners", "g", "0", True, "VAT16"),
    ("FAST-OLD", "Rusty bolt mix", "Fasteners", "piece", "0", False, "VAT16"),
    ("TAPE-DUCT", "Duct tape 50m", "Misc", "piece", "10", True, "VAT16"),
    ("GLUE-EPOXY", "Epoxy glue 2-part", "Misc", "piece", "0", True, "VAT16"),
    ("ROPE-10", "Poly rope 10mm 50m", "Misc", "m", "5", True, "VAT16"),
    ("CEMENT-MIX", "Ready-mix concrete 25kg", "Misc", "kg", "20", True, "VAT16"),
    ("MISC-OLD", "Unknown hardware lot", "Misc", "piece", "0", False, "VAT16"),
    ("LEG-001", "Legacy item A", "Legacy stock", "piece", "0", True, "VAT_EXEMPT"),
    ("LEG-002", "Legacy item B", "Legacy stock", "piece", "0", True, "VAT_EXEMPT"),
    ("LEG-003", "Legacy item C", "Legacy stock", "kg", "0", True, "VAT_EXEMPT"),
)

