# Generated by Django 6.1 on 2026-08-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_purchaseorder_approved_gross_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderchangelog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('field_updated', 'Field updated'), ('line_added', 'Line added'), ('line_updated', 'Line updated'), ('line_removed', 'Line removed'), ('goods_received', 'Goods received')], max_length=30),
        ),
    ]
