# Generated by Django 6.1 on 2026-08-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_purchaseorderchangelog_action'),
        ('products', '0006_unique_primary_supplier_item_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'item'), name='unique_po_line_item'),
        ),
    ]
