# Generated by Django 6.1 on 2026-08-21 10:07

import django.db.models.deletion
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


def seed_default_limits(apps, schema_editor):
    ApprovalLimit = apps.get_model("procurement", "ApprovalLimit")
    defaults = (
        ("warehouse_managers", 2, Decimal("5000.00"), Decimal("100.00")),
        ("warehouse_managers", 3, Decimal("50000.00"), Decimal("500.00")),
    )
    for group_name, grade, approval, self_approval in defaults:
        ApprovalLimit.objects.get_or_create(
            group_name=group_name,
            grade=grade,
            defaults={
                "approval_limit": approval,
                "self_approval_limit": self_approval,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0004_unique_po_line_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalLimit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_name", models.CharField(max_length=64)),
                ("grade", models.PositiveSmallIntegerField()),
                (
                    "approval_limit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Max PO gross (EUR) this grade may approve for another user's PO.",
                        max_digits=14,
                    ),
                ),
                (
                    "self_approval_limit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Max PO gross (EUR) this grade may approve on a PO they created.",
                        max_digits=14,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["group_name", "grade"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group_name", "grade"),
                        name="unique_approval_limit_group_grade",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("approval_limit__gte", 0)),
                        name="approval_limit_gte_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("self_approval_limit__gte", 0)),
                        name="self_approval_limit_gte_zero",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ApprovalLimitChangeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("created", "Created"), ("updated", "Updated")], max_length=30)),
                ("changes", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approval_limit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="procurement.approvallimit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_limit_change_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(seed_default_limits, migrations.RunPython.noop),
    ]
