# Generated by Django 6.1.1 on 2026-09-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
