# Generated by Django 6.1 on 2026-08-21 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('procurement', '0006_alter_purchaseorder_status'),
        ('products', '0008_alter_item_reorder_level_alter_item_retail_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchApprovalLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=16, unique=True)),
                ('approval_limit', models.DecimalField(decimal_places=2, help_text="Max gross (EUR) a manager may approve for another user's request.", max_digits=14)),
                ('self_approval_limit', models.DecimalField(decimal_places=2, help_text='Max gross (EUR) a manager may approve on a request they created.', max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role'],
                'constraints': [models.CheckConstraint(condition=models.Q(('approval_limit__gte', 0)), name='branch_approval_limit_gte_zero'), models.CheckConstraint(condition=models.Q(('self_approval_limit__gte', 0)), name='branch_self_approval_limit_gte_zero')],
            },
        ),
        migrations.CreateModel(
            name='BranchApprovalLimitChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], max_length=30)),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch_approval_limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='orders.branchapprovallimit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_approval_limit_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilling', 'Fulfilling'), ('shipped', 'Shipped'), ('received', 'Received'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_net', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('approved_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('approved_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('warehouse_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_requests', to='branches.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_requests_created', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_requests_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalRequestChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('field_updated', 'Field updated'), ('line_added', 'Line added'), ('line_updated', 'Line updated'), ('line_removed', 'Line removed')], max_length=30)),
                ('changes', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internal_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_logs', to='orders.internalrequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_request_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('internal_code', models.CharField(blank=True, max_length=64)),
                ('unit_of_measure', models.CharField(blank=True, max_length=16)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.internalrequest')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_request_lines', to='products.item')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procurement.purchaseorder')),
                ('purchase_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procurement.purchaseorderline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InternalRequestLineChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('removed', 'Removed')], max_length=30)),
                ('changes', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internal_request_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='orders.internalrequestline')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_request_line_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='internalrequestline',
            constraint=models.UniqueConstraint(fields=('internal_request', 'item'), name='unique_request_line_item'),
        ),
    ]
