# Generated by Django 6.1.1 on 2026-09-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_internalrequest_client_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalrequestline',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='internalrequestline',
            name='quantity_reserved',
            field=models.IntegerField(default=0),
        ),
    ]
