# Generated by Django 6.1 on 2026-08-20 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_item_internal_code_ci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyproduct',
            options={'ordering': ['name'], 'verbose_name': 'family', 'verbose_name_plural': 'families'},
        ),
        migrations.AddField(
            model_name='item',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='special_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='SupplierItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_prices', to='products.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_prices', to='products.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierItemPriceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deactivated', 'Deactivated'), ('reactivated', 'Reactivated')], max_length=20)),
                ('changes', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_item_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_logs', to='products.supplieritemprice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_item_price_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplieritemprice',
            constraint=models.UniqueConstraint(fields=('supplier', 'item'), name='unique_supplier_item_price'),
        ),
    ]
