# Generated by Django 6.1 on 2026-08-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_familyproduct_options_item_retail_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Cached stock balance — updated only via StockMovement.', max_digits=12),
        ),
    ]
