# Generated by Django 6.1 on 2026-08-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_item_quantity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supplieritemprice',
            constraint=models.UniqueConstraint(condition=models.Q(('primary', True)), fields=('item',), name='unique_primary_supplier_item_price'),
        ),
    ]
