# Generated by Django 6.1 on 2026-08-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_unique_primary_supplier_item_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='item_quantity_gte_zero'),
        ),
    ]
