# Generated by Django 6.1 on 2026-08-21 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_item_quantity_gte_zero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='reorder_level',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='special_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='supplieritempricechangelog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vatrate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_level__gte', 0)), name='item_reorder_level_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('retail_price__gte', 0)), name='item_retail_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('wholesale_price__gte', 0)), name='item_wholesale_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('special_price__gte', 0)), name='item_special_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='vatrate',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 1)), name='vat_rate_gte_zero_lte_one'),
        ),
    ]
