# Generated by Django 6.1 on 2026-08-23 08:57

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_item_reorder_level_alter_item_retail_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_families', to='products.familyproduct')),
            ],
            options={
                'verbose_name': 'sub-family',
                'verbose_name_plural': 'sub-families',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='sub_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='products.subfamily'),
        ),
        migrations.CreateModel(
            name='SubFamilyChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deactivated', 'Deactivated'), ('reactivated', 'Reactivated')], max_length=20)),
                ('changes', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_logs', to='products.subfamily')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_family_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='subfamily',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('family'), name='unique_subfamily_name_ci_per_family'),
        ),
    ]
