# Generated by Django 6.1.1 on 2026-09-17 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_subfamily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Cached stock balance — updated only via StockMovement.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='reorder_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
